#!/bin/bash
# This scripts starts and restarts, if necessary, the rtl433_reader.py program.
# Sleep for a minute, as some rtl-sdr programs need that time to run successfully.
sleep 60

until /home/pi/pi_logger/rtl433_reader.py; do
    echo "Server 'rtl433_reader.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done
