#!/bin/bash
# This scripts starts and restarts, if necessary, the meter_reader.py program.

# Sleep for a minute, as rtlamr seems to need that time to run successfully.
sleep 60

# Need to start the rtl_tcp program
/home/pi/pi_logger/scripts/run_rtl_tcp &

until /home/pi/pi_logger/meter_reader.py; do
    echo "Server 'meter_reader.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done
