#!/bin/bash
# This scripts starts and restarts, if necessary, the meter_reader.py program.

# Sleep for awhile to wait for NTP clock setting to work.
sleep 35

# Need to start the rtl_tcp program
/home/pi/pi_logger/scripts/run_rtl_tcp &

# Give rtl_tcp time to start up before starting rtlamr.  Without wating
# rtlamr start-up was not reliable
sleep 5

until /home/pi/pi_logger/meter_reader.py; do
    echo "Server 'meter_reader.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done
