#!/bin/bash
sleep 10  # wait for modem switch
until /usr/bin/wvdial -C /boot/pi_logger/wvdial.conf `/home/pi/pi_logger/scripts/get_setting.py CELL_MODEM_MODEL`; do
    echo "Script wvdial crashed with exit code $?. Respawning.." >&2
    sleep 3
done

